name:                fillit
version:             0.1.0.0
synopsis:            Flexible string substitution
description:         Please see README.md
homepage:            https://github.com/ishiy1993/fillit#readme
license:             BSD3
author:              ishiy <y.ishihara.1993@gmail.com>
maintainer:          ishiy <y.ishihara.1993@gmail.com>
copyright:           (c) 2017 ishiy
category:            Text
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - unordered-containers

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - data-default
    - parsec
    - text

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - fillit
  doctests:
    main: doctests.hs
    source-dirs: test
    dependencies:
      - doctest
